binary-level: false
checkpoint-early-stop-patience: 0
checkpoint-keep-only-best: 3
checkpoint-save: true
checkpoint-validation-steps: 300000
config: predest_config.yml
debug: false
dropout-est: 0.0
dropout-pred: 0.0
embedding-sizes: 0
epochs: 1
gaps-bad-weight: 3.0
gpu-id: -1
hidden-est: 125
hidden-pred: 100
learning-rate: 0.002
learning-rate-decay: 1.0
learning-rate-decay-start: 0
load-model: trained_models/estimator_en_de.torch/estimator_en_de.torch
log-interval: 100
mlflow-always-log-artifacts: false
mlflow-tracking-uri: mlruns/
mlp-est: true
model: estimator
optimizer: adam
out-embeddings-size: 200
predict-gaps: false
predict-inverse: false
predict-side: tags
predict-source: false
predict-target: true
quiet: false
resume: false
rnn-layers-est: 1
rnn-layers-pred: 2
seed: 42
sentence-level: true
sentence-ll: false
sentence-ll-predict-mean: false
share-embeddings: false
source-bad-weight: 2.5
source-embeddings-size: 50
source-max-length: .inf
source-min-length: 0
source-vocab-min-frequency: 1
start-stop: false
target-bad-weight: 2.5
target-embeddings-size: 50
target-max-length: .inf
target-min-length: 0
target-vocab-min-frequency: 1
token-level: true
train-batch-size: 64
train-pe: WMT19/small/train.pe
train-sentence-scores: WMT19/small/train.hter
train-source: WMT19/small/train.src
train-target: WMT19/small/train.mt
train-target-tags: WMT19/small/train.tags
use-probs: false
valid-batch-size: 64
valid-pe: WMT19/dev.pe
valid-sentence-scores: WMT19/dev.hter
valid-source: WMT19/dev.src
valid-target: WMT19/dev.mt
valid-target-tags: WMT19/dev.tags
warmup: 0
wmt18-format: true
