add-embeddings-vocab: false
bad-weight: 3.0
checkpoint-early-stop-patience: 10
checkpoint-keep-only-best: 1
checkpoint-save: true
dropout: 0.0
embeddings-dropout: 0.5
epochs: 3
freeze-embeddings: false
gpu-id: -1
hidden-sizes:
- 400
- 200
- 100
- 50
init-support: 0.1
init-type: uniform
keep-rare-words-with-embeddings: true
learning-rate: 0.001
log-interval: 100
max-aligned: 5
model: nuqe
optimizer: adam
output-dir: runs/nuqe
predict-target: true
seed: 42
source-embeddings-size: 50
source-pos-embeddings-size: 20
source-vocab-min-frequency: 2
target-embeddings-size: 50
target-pos-embeddings-size: 20
target-vocab-min-frequency: 2
train-alignments: WMT19/train.src-mt.alignments
train-batch-size: 64
train-source: WMT19/train.src
train-target: WMT19/train.mt
train-target-tags: WMT19/train.tags
valid-alignments: WMT19/dev.src-mt.alignments
valid-batch-size: 64
valid-source: WMT19/dev.src
valid-target: WMT19/dev.mt
valid-target-tags: WMT19/dev.tags
window-size: 3
wmt18-format: true
