binary-level: false
checkpoint-early-stop-patience: 0
checkpoint-keep-only-best: 3
checkpoint-save: true
checkpoint-validation-steps: 300000
dropout-est: 0.0
epochs: 1
gpu-id: -1
hidden-est: 125
learning-rate: 2e-3
load-model: trained_models/estimator_en_de.torch/estimator_en_de.torch
log-interval: 100
mlp-est: true
model: estimator
rnn-layers-est: 1
sentence-level: true
sentence-ll: false
source-bad-weight: 2.5
target-bad-weight: 2.5
token-level: true
train-batch-size: 64
train-pe: WMT19/small/train.pe
train-sentence-scores: WMT19/small/train.hter
train-source: WMT19/small/train.src
train-target: WMT19/small/train.mt
train-target-tags: WMT19/small/train.tags
valid-batch-size: 64
valid-pe: WMT19/dev.pe
valid-sentence-scores: WMT19/dev.hter
valid-source: WMT19/dev.src
valid-target: WMT19/dev.mt
valid-target-tags: WMT19/dev.tags
wmt18-format: true
